### ISSUE TITLE
少个 libX11-xcb 的依赖

### ISSUE THREAD

**Issue by jianingy** [sigoden/wechat-devtools#1]
启动的时候会报
`
/app/nw: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

Dockerfile 加上 apt-get install 后面加上 libx11-xcb1  就 OK 了.

**Comment by xiaoguo0426** [comment]
@jianingy 哥们～好像加上了好像还是报这个错呢。。宿主机环境  ubuntu16.04   Dockerfile已是最新
